Remove the use of mockStatic so that problematic mockito-inline can be dropped
With mockito-inline enabled, at least the below 2 tests are failing:

- org.apache.hadoop.hbase.TestHBaseTestingUtil

Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

- org.apache.hadoop.hbase.security.access.TestRpcAccessChecks

java.lang.NullPointerException: Cannot invoke "org.apache.hbase.thirdparty.com.google.protobuf.Descriptors$ServiceDescriptor.getFullName()" because "service" is null
	at org.apache.hadoop.hbase.ipc.CoprocessorRpcUtils.getServiceName(CoprocessorRpcUtils.java:77)
	at org.apache.hadoop.hbase.master.HMaster.registerService(HMaster.java:3479)

The later is especially weird. The NPE should be ocuring even now as the mock is not stubbed, but it is somehow working.