HBASE-27802 Manage static javascript resources programatically (#7032)
* HBASE-27802 Manage static javascript resources programatically (#6864)

Signed-off-by: Nick Dimiduk <ndimiduk@apache.org>
Signed-off-by: Nihal Jain <nihaljain@apache.org>
(cherry picked from commit 2f9d9fcd906c30abf30da1b5a78eae948e901e30)

* HBASE-27802 Manage static javascript resources programatically (addendum: Fix not working popovers on UI)

Popovers were not working on the UI and the following JS error was logged to browser console:

```
Uncaught TypeError: i.createPopper is not a function
```

This is because popper.js was not available on the page for Bootstrap.

Solution: We use bootstrap.bundle.min.js instead which includes both popper.js and Bootstrap.

---------

Signed-off-by: Nick Dimiduk <ndimiduk@apache.org>
Signed-off-by: Nihal Jain <nihaljain@apache.org>