[HBASE-5535] Make the functions in task monitor synchronized
Summary:
There are some potential race condition in the task monitor. So update the functions in task monitor to be synchronized.

The example of the problem caused by the race condition:
ERROR org.apache.hadoop.hbase.regionserver.MemStoreFlusher: Cache flush failed for region
java.lang.IndexOutOfBoundsException: Index: 1745, Size: 1744
at java.util.ArrayList.add(ArrayList.java:367)
at java.util.SubList.add(AbstractList.java:633)
at java.util.SubList.add(AbstractList.java:633)
at java.util.SubList.add(AbstractList.java:633)
at java.util.SubList.add(AbstractList.java:633)
at java.util.SubList.add(AbstractList.java:633)
at java.util.AbstractList.add(AbstractList.java:91)
at org.apache.hadoop.hbase.monitoring.TaskMonitor.createStatus(TaskMonitor.java:74)
at org.apache.hadoop.hbase.regionserver.HRegion.flushcache(HRegion.java:1139)
at org.apache.hadoop.hbase.regionserver.MemStoreFlusher.flushRegion(MemStoreFlusher.java:260)
at org.apache.hadoop.hbase.regionserver.MemStoreFlusher.flushRegion(MemStoreFlusher.java:234)
at org.apache.hadoop.hbase.regionserver.MemStoreFlusher.run(MemStoreFlusher.java:146)

Test Plan: running all the unit tests

Reviewers: kannan, pkhemani

Reviewed By: pkhemani

CC: hbase-eng@lists

Differential Revision: https://phabricator.fb.com/D422810

Task ID: 958785, 956527

git-svn-id: https://svn.apache.org/repos/asf/hbase/branches/0.89-fb@1298670 13f79535-47bb-0310-9956-ffa450edef68