HBASE-29878 Improve the Documentation UI (addendum) (#7853)
Add back Maven site plugin to fix the warning during javadoc generation.

[WARNING] An issue has occurred with maven-javadoc-plugin:3.4.0:aggregate-no-fork report, skipping LinkageError Receiver class org.apache.maven.plugins.javadoc.AggregatorJavadocNoForkReport does not define or inherit an implementation of the resolved method 'abstract void generate(org.codehaus.doxia.sink.Sink, java.util.Locale)' of interface org.apache.maven.reporting.MavenReport., please report an issue to Maven dev team.
java.lang.AbstractMethodError: Receiver class org.apache.maven.plugins.javadoc.AggregatorJavadocNoForkReport does not define or inherit an implementation of the resolved method 'abstract void generate(org.codehaus.doxia.sink.Sink, java.util.Locale)' of interface org.apache.maven.reporting.MavenReport.

Signed-off-by: Duo Zhang <zhangduo@apache.org>
Signed-off-by: Nihal Jain <nihaljain@apache.org>