HBASE-22345 REST Server must have specific version of javax.annotations available at runtime
Rest Server throws NoClassDefFoundError : javax/annotation/Priority after buiding with JDK8 and running on JDK8

Signed-off-by: Sean Busbey <busbey@apache.org>
(cherry picked from commit 68f14c19ff79e36b17e99c7e848c19ce5e0164d5)