HBASE-29352 Use JRuby 9.2.21.0 to fix shell on Apple M-series processors (#7030)
Upgrade JRuby to 9.2.21.0 to fix the following error when launching HBase shell
on Apple M-series systems:

    NotImplementedError: fstat unimplemented unsupported or native support failed to load

9.2.21.0 is the final release in 9.2 line and the minimum version required
to fix the issue.

Reference: https://github.com/jruby/jruby/releases/tag/9.2.21.0

> Support for Apple's M processors has been backported.
> It has not been heavily tested, but it has been confirmed working by users.

Signed-off-by: Nihal Jain <nihaljain@apache.org>