Fix 2 unit test failure
Summary:
TestGlobalMemStoreSize fails because the total region number = region number +2
(root and meta). [Fixed]

TestHeapSize fails because the HRegion has 1 more reference now. [Fixed]

TestReplicationSource fails because "
Caused by: java.io.IOException: java.io.FileNotFoundException:
java.io.FileNotFoundException: Parent directory doesn't exist:
/user/mvaradachari/.logs"
I will keep work on this.

TestAdmin fails because timeout when disable the table. Actually I cannot
reproduce this problem. I attempt several times. The unit test always passed

Test Plan:
passing unit tests

Reviewed By: nspiegelberg
Reviewers: jgray, nspiegelberg, kannan
CC: nspiegelberg, awolff, hbase@lists
Revert Plan:
OK

Differential Revision: 228874

git-svn-id: https://svn.apache.org/repos/asf/hbase/branches/0.89@1181510 13f79535-47bb-0310-9956-ffa450edef68