HBASE-28298 HFilePrettyPrinter thrown NoSuchMethodError about MetricRegistry (#5783)
Co-authored-by: mrzhao <mrzhao@iflytek.com>
Signed-off-by: Duo Zhang <zhangduo@apache.org>
(cherry picked from commit fb94e1e733f734fd245c0333a795eaabc1243bc7)