[jira] [HBASE-6943] [89-fb] Do not catch certain exceptions trying to get an RS connection
Author: mbautin

Summary: When getting a regionserver connection in 0.89-fb in HBaseClient, we catch all types of Throwable. I have observed a real case when the client looked stuck. On debugging it turned out that a NoSuchMethodError was thrown and caught, leaving the connection in an inconsistent state (initialized socket but null streams). All following attempts resulted in NPEs that were also caught, and no errors were logged. From the user's perspective the client was just stuck. The root cause was the absence of a required jar (hence the NoSuchMethodError) but it was not reported properly.

Test Plan: Run a client with the same configuration as before and verify it does not get stuck.

Reviewers: kannan, liyintang, kranganathan

Reviewed By: kannan

CC: avf, adela, pritamdamania, aaiyer, nspiegelberg, amirshim, mycnyc

Differential Revision: https://reviews.facebook.net/D5877

git-svn-id: https://svn.apache.org/repos/asf/hbase/branches/0.89-fb@1394307 13f79535-47bb-0310-9956-ffa450edef68