HBASE-27030 Fix undefined local variable error in draining_servers.rb (#4427)
HBASE-21812 replaced a for-loop with an each block.
Each block introduces a new scope, so a local variable defined inside it
cannot be accessed afterwards.

  NameError: undefined local variable or method `admin' for main:Object
    getServerNames at /opt/khp/hbase/bin/draining_servers.rb:81
        addServers at /opt/khp/hbase/bin/draining_servers.rb:88
            <main> at /opt/khp/hbase/bin/draining_servers.rb:146

This commit defines the admin local variable in the current scope beforehand,
so that we can still access it after the block.

Signed-off-by: Duo Zhang <zhangduo@apache.org>
(cherry picked from commit 2b573ae377be926922f48238c4da45a2289f318f)
Change-Id: Id7026f6f46e2149d458d1b69db82143fea5ba9aa